name: Build Electron

on:
  push:
    branches:
      - main
    paths:
      - 'fc-app/electron/package.json'

  workflow_dispatch:
  
jobs:
  build-electron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
          
      - name: Setup wine for Windows build
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y \
            wine32 wine64 \
            bsdtar fpm pacman fakeroot libarchive-tools rpm

      - name: Install dependencies
        run: |
          cd fc-app/electron
          npm install
          npm install -g typescript tsc-alias

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.FC_DESKTOP_TOKEN }}
        run: |
          cd fc-app/electron
          npm run build:ts
          npx electron-builder --publish always --win --linux
