name: Copy Electron Files and Trigger Build

on:
  push:
    paths:
      - 'fc-app/electron/**'

jobs:
  copy-and-trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Copy Electron files to the target repository
        run: |
          git clone https://github.com/wxn0brP/fc-desktop.git fc-desktop
          cp -r fc-app/electron/* fc-desktop/
          cd fc-desktop
          git config user.name "wxn0brP"
          git config user.email "fusion@fusion.ct8.pl"
          git add .
          git commit -m "Update Electron files from fusion-chat"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
