name: React Native Android Build and Publish

on:
  push:
    paths:
      - 'fc-app/fc-mobile/**'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install npm dependencies
        run: |
          cd fc-app/fc-mobile
          npm install

      - name: Build Android Release
        run: |
          cd fc-app/fc-mobile/android
          ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: fc-app/fc-mobile/android/app/build/outputs/apk/release/

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./fc-app/fc-mobile/package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release in Target Repository
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FC_DESKTOP_TOKEN }}
          ACTIONS_STEP_DEBUG: true
        with:
          repository: wxn0brP/fc-mobile
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: Release of Fusion Chat APK version ${{ env.VERSION }}
          draft: true
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FC_DESKTOP_TOKEN }}
          ACTIONS_STEP_DEBUG: true
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fc-app/fc-mobile/android/app/build/outputs/apk/release/app-release.apk
          asset_name: fusion-chat-${{ env.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive